server:
  port: 1000

spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: eurekaServer1000
#    prefer-ip-address: false
  client:
    #是否向服务注册中心注册自己，集群需要注册中心相互注册
    register-with-eureka: true
    #是否从服务注册中心拉取服务列表，客户端才需要向服务注册中心拉取服务列表
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaServer1001:1001/eureka/

